version: '3.4'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 15432
        protocol: tcp
    networks:
      - db
  
  adminer:
    image: adminer
    restart: always
    ports:
      - target: 8080
        published: 8181
        protocol: tcp
    depends_on:
      - db
    networks:
      - db

  unilime-test:
    build: .
    restart: always
    environment:
      DATABASE_SERVER: db
      DB_NAME: ${DB_NAME}
      DB_NAME_TEST: ${DB_NAME_TEST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_SERVER_PROD}/${DB_NAME}
      DB_URL_SYNC: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_SERVER_PROD}/${DB_NAME}
      DB_URL_TEST: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_SERVER}/${DB_NAME_TEST}
      DB_DEBUG: ${DB_DEBUG}
    networks:
      - db
    ports:
      - target: 5000
        published: 5001
        protocol: tcp
    depends_on:
      - db

networks:
  db: {}

volumes:
  db:
